- name: configure httpd
  hosts: localhost

  tasks:

  - name: Install packages
    yum: name={{ item }} state=latest
    with_items:
    - httpd
    - stress
    
  - name: Copy web content
    copy: src=files/index.php dest=/var/www/html/index.php owner=root group=root
    notify:
    - restart apache

  handlers:

  - name: restart apache
    service: name=httpd state=restarted


